feat: Disable SMS Auth Activation if SMS Gateway is not provided
OpenSourcePolitics/decidim-module-half_sign_up pull request #41
Opened 2024-07-26 11:29 UTC by AyakorK

### 🎩 Description

This PR has been made to disable the fact that you can activate the SMS authentication if you have not gateway provided.

### **⚠️ 🚨 It will automatically be enabled in local due to the fact that we have the SMS:ExampleGateway then please follow the test process to make sure that the feature works.

### 🔧 How to test

#### ⚠️ Engineering Setup ⚠️ 
- Generate your development app
- Access to your development_app files `config/decidim.rb``
- Go to line 225 and comment this line : 
 `  config.sms_gateway_service = 'Decidim::Verifications::Sms::ExampleGateway' `
- Execute your app 

##### 🌓 First Test
- Log as an Admin
- Access BackOffice
- Access to Settings and Authentication Settings
- Make sure that the checkbox for the sms authentication is disabled
- Try to enable the email authentication and make sure everything works

#### 😈 Second Test
- Log as an Admin
- Access BackOffice
- Access to Settings and Authentication Settings
- Make sure that the checkbox for the sms authentication is disabled
- Try to access HTML directly on your page (Right Click + Inspect)
- Search for the disabled checkbox and on the HTML modify it and get rid of the `disabled:"disabled"`
- Activate the field SMS Authentication
- Update the Org
- Make sure an error is appearing and that the method is not enabled

#### 👿 Third Test
- Reenable the ExampleGateway (uncomment the line in the config/decidim.rb file
- Relaunch your app
- Activate the sms authenticator
- Update the org
- Close your app (ctrl+C in your terminal)
- Comment the Gateway (comment the line)
- Try to update the methods using the email authentication
- Make sure when you update the org that the sms method has been disabled and that it still updated

### 🔨 Tasks

- [x] Update the command to ensure backend security
- [x] Modify the controller to add a new error management (:sms_service_not_configured)
- [x] Modify the view to disable the checkbox
- [x] Add locales
- [x] Add tests

2024-07-29 15:44 UTC, luciegrau approved these changes
Works great, thank you! 🚀

2024-08-01 10:53 UTC, Quentinchampenois requested changes
Thanks for the PR, I have some refactor suggestions to be more readable and prevent any flaky specs on CI using mocks

2024-08-01 10:53 UTC, Quentinchampenois commented on app/commands/decidim/half_signup/admin/update_auth_settings.rb
> +        def check_sms_service
Prefer to rename method `sms_gateway_service_configured?` or more explicit name

2024-08-01 10:53 UTC, Quentinchampenois commented on spec/commands/decidim/half_signup/admin/update_auth_settings_spec.rb
> +    Decidim.configure do |config|
Prefer to define mock for `Decidim.configure.sms_gateway_service` 

Example : `allow(Decidim.config.sms_gateway_service).to receive(:present?).and_return(true)`

2024-08-01 10:53 UTC, Quentinchampenois commented on spec/commands/decidim/half_signup/send_verification_spec.rb
> +    Decidim.configure do |config|
Prefer to define mock for `Decidim.configure.sms_gateway_service` 

Example : `allow(Decidim.config.sms_gateway_service).to receive(:present?).and_return(true)`

2024-08-01 10:53 UTC, Quentinchampenois commented on spec/controllers/decidim/half_signup/quick_auth_controller_spec.rb
> +    Decidim.configure do |config|
Prefer to define mock for `Decidim.configure.sms_gateway_service` 

Example : `allow(Decidim.config.sms_gateway_service).to receive(:present?).and_return(true)`

2024-08-01 10:53 UTC, Quentinchampenois commented on spec/system/add_update_phone_number_spec.rb
> +    Decidim.configure do |config|
Prefer to define mock for `Decidim.configure.sms_gateway_service` 

Example : `allow(Decidim.config.sms_gateway_service).to receive(:present?).and_return(true)`

2024-08-01 10:53 UTC, Quentinchampenois commented on spec/system/admin_manage_auth_settings_spec.rb
> +    Decidim.configure do |config|
Prefer to define mock for `Decidim.configure.sms_gateway_service` 

Example : `allow(Decidim.config.sms_gateway_service).to receive(:present?).and_return(true)`

2024-08-01 10:53 UTC, Quentinchampenois commented on spec/system/admin_manage_auth_settings_spec.rb
> +    Decidim.configure do |config|
Prefer to define mock for `Decidim.configure.sms_gateway_service` 

Example : `allow(Decidim.config.sms_gateway_service).to receive(:present?).and_return(true)`

2024-08-01 10:53 UTC, Quentinchampenois commented on spec/system/admin_manage_auth_settings_spec.rb
> +    Decidim.configure do |config|
Prefer to define mock for `Decidim.configure.sms_gateway_service` 

Example : `allow(Decidim.config.sms_gateway_service).to receive(:present?).and_return(true)`

2024-08-01 10:53 UTC, Quentinchampenois commented on spec/system/admin_manage_auth_settings_spec.rb
> +  it "shows a warning message when the SMS gateway service is not configured" do
Should be moved in a `context` `"SMS gateway service is not present"`

2024-08-01 10:53 UTC, Quentinchampenois commented on spec/system/budgets_view_spec.rb
> +    Decidim.configure do |config|
Prefer to define mock for `Decidim.configure.sms_gateway_service` 

Example : `allow(Decidim.config.sms_gateway_service).to receive(:present?).and_return(true)`

2024-08-05 10:52 UTC, AyakorK commented
Hey @Quentinchampenois, I made some changes and now everything returns to the initial state after execution.

I also replaced the direct configuration with "allow" to make it more compliant with RSpec rules. However, I couldn't change the [spec/commands/decidim/half_signup/send_verification_spec.rb](https://github.com/OpenSourcePolitics/decidim-module-half_sign_up/pull/41/files/d907559723cf5bfae7dfba552d66669f481d1184#diff-51b979d77aa2412112037c826d70fc83f7cb9cd0cfd73243e53eddd96eb7fb69) file, as it caused the test to fail every time despite multiple attempts.

I hope this pleases you. If you have any feedback to improve this code, I'll be happy to implement it, but I think it seems stable enough for now! 😄

2024-08-07 08:49 UTC, Quentinchampenois approved these changes

2024-08-07 08:50 UTC, merged